// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABW1r8_tdYiY0__D6HJFxB7VyGHVWPhLI',
    appId: '1:774428086159:web:9f4f65b226fe792bb985fa',
    messagingSenderId: '774428086159',
    projectId: 'gestureai-30380',
    authDomain: 'gestureai-30380.firebaseapp.com',
    storageBucket: 'gestureai-30380.firebasestorage.app',
    measurementId: 'G-2CYYP43JCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfUJdmxXmFSGohjjLjVoj320xc6fwXo04',
    appId: '1:774428086159:android:3873da95e617df4bb985fa',
    messagingSenderId: '774428086159',
    projectId: 'gestureai-30380',
    storageBucket: 'gestureai-30380.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8kvMm4Bufx9WMD-HUXdxRo4G_SOphYE8',
    appId: '1:774428086159:ios:99bd322285217fd4b985fa',
    messagingSenderId: '774428086159',
    projectId: 'gestureai-30380',
    storageBucket: 'gestureai-30380.firebasestorage.app',
    iosBundleId: 'com.example.handsingdetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8kvMm4Bufx9WMD-HUXdxRo4G_SOphYE8',
    appId: '1:774428086159:ios:99bd322285217fd4b985fa',
    messagingSenderId: '774428086159',
    projectId: 'gestureai-30380',
    storageBucket: 'gestureai-30380.firebasestorage.app',
    iosBundleId: 'com.example.handsingdetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABW1r8_tdYiY0__D6HJFxB7VyGHVWPhLI',
    appId: '1:774428086159:web:88fad8462487e4f5b985fa',
    messagingSenderId: '774428086159',
    projectId: 'gestureai-30380',
    authDomain: 'gestureai-30380.firebaseapp.com',
    storageBucket: 'gestureai-30380.firebasestorage.app',
    measurementId: 'G-QQGNRGLNM0',
  );

}